language: php

php:
  - 7.2

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.testing .env
  - sudo mysql -e "CREATE DATABASE `votings_test`;"
  - sudo mysql -e "CREATE USER `votings_test` IDENTIFIED BY 'votings_test';"
  - sudo mysql -e "GRANT ALL ON `votings_test`.* TO `votings_test`@`localhost`;"
  - sudo mysql -e "FLUSH PRIVILEGES;"
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit
