language: php

php:
  - 7.2

addons:
  mariadb: 15.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database votings_test;'
  - composer self-update
  - composer install --no-interaction

cache:
  directories:
    - node_modules
    - vendor

script:
  - php artisan key:generate
  - vendor/bin/phpunit
